//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCVSitesi_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEGITIM
    {
        public int ID { get; set; }
        public string UNIVERSITE { get; set; }
        public string FAKULTE { get; set; }
        public string BOLUM { get; set; }
        public Nullable<decimal> NOTORTALAMA { get; set; }
    }
}
